### ISSUE TITLE
OS X version

### ISSUE THREAD

**Issue by avinassh** [neo1691/scorer.py#11]
I have built an [OS X version](https://github.com/avinassh/score-notify), shall I send a PR which mentions the same in README.MD?

**Comment by neo1691** [comment]
Hi @avinassh Awesome that you have built an OS X version. I don't know if you can send me PR if you haven't forked my repository. 

Also I saw your code, it is a standalone OS X version. Can you integrate the code with my code? So that it runs the same on all the version? You will need to add checks using the os that the user is using before running the script. I think it can be done using os.name or platform.platform() or platform.system() or sys.platform.

Go ahead fork my repo, switch to a new branch, hack you way ahead, and then send me a PR. Thanks a lot.

**Comment by avinassh** [comment]
Yes, I haven't forked your project and started separately. Reason is, for OS X instructions are bit different and requires extra installation of libraries outside `pip`. First user needs to install `brew` and `terminal-notifier`, these are outside `pip`. Readme instructions will become cumbersome and confusing. I also saw this latest issue #2, I don't see any such restrictions in OS X. Plus I don't have linux installed and can't run tests. Thats why I thought a separate project will be nice. So may be we can mention in Readme about OS X version and development can be independent. 

What do you say?

**Comment by neo1691** [comment]
Ah, sure. Why not. Do send me a PR with a link to your script in README.md. 

But just as a suggestion, I would like to research a bit on how to make a script cross platform? 
I have seen the same scripts running on both Linux/unix as well as OSX. I don't have a mac with me, so I can't even test it. Would be great to have someone with a mac in the team :) 

But for the time being, please send me a PR with a modification in the README.md so that I can merge it right away. 

Cheers

**Comment by avinassh** [comment]
Sure, sending a PR now. 

Even I am interested to know how to make script cross platform, will do bit of research. Thanks!

**Comment by neo1691** [comment]
You can use the platform module. Check it out.
