### ISSUE TITLE
No JSON objects could be decoded

### ISSUE THREAD

**Issue by himanshusoni** [neo1691/scorer.py#22]
Getting the mention error.
I ran the script when no matches were available. That's all i think might be the cause for this.

 
Fetching matches..
INFO:root:Sending requests
INFO:urllib3.connectionpool:Starting new HTTP connection (1): static.cricinfo.com
DEBUG:urllib3.connectionpool:Setting read timeout to None
DEBUG:urllib3.connectionpool:"GET /rss/livescores.xml HTTP/1.1" 200 2657
INFO:urllib3.connectionpool:Starting new HTTP connection (1): www.espncricinfo.com
DEBUG:urllib3.connectionpool:Setting read timeout to None
DEBUG:urllib3.connectionpool:"GET /netstorage/656493.json HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Setting read timeout to None
DEBUG:urllib3.connectionpool:"GET /ci/engine/match/656493.json?view=live;wrappertype=live;zakamai=1 HTTP/1.1" 200 21863
Traceback (most recent call last):
  File "scorer.py", line 77, in <module>
    parsingJson = json.loads(dataFromJSONUrl.text)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by neo1691** [comment]
Hi, this is because of #21 that it is happening. I have fixed this bug in my local repo, I will push the changes once I get the folder structure right. 
Thanks for reporting.

**Comment by saurabh-deochake** [comment]
@neo1691 Good news! Please push it asap. I have been working on this since yesterday.

**Comment by neo1691** [comment]
I was stuck with some other work until now, but now I have some time to work on this again!!

**Comment by neo1691** [comment]
@saurabh-deochake Please have a look at the structureCode branch. I need to understand the json better. Right now the script is working, but because we do not know how the json is structured, the code that parses the json breaks when there is a key error. 

So I don't know now which fields in the json gives me the runs, overs and wickets. I think the fields in the json changes according to the match innings. 

I am using this tool to go through the json 
http://jsonviewer.stack.hu/

Here is the url for the Australia vs India match
http://www.espncricinfo.com/ci/engine/match/656495.json

And here's is a url of a test match that's is happening now in Sri lanka.
http://www.espncricinfo.com/ci/engine/match/801467.json

@himanshusoni  @thefourtheye @asdofindia @surajssd  Please have a look.

**Comment by asdofindia** [comment]
I was using centre for getting runs and wicket. But the Sri Lanka match has nothing in it. 
innings might be useful. Didn't see it in the past.

There can always be some fields missing. Catching KeyError exception would be nice. At least it'll skip over the errors. Maybe a notification can be thrown if there're too many exceptions raised.

**Comment by neo1691** [comment]
Yeah I was also thinking the same, but if we understood how the json is structured according to the types of matches(international, domestic, t20, test, oneday etc) we have a better chance of handling the errors!

**Comment by thefourtheye** [comment]
Hmmm, I am wondering if they have any public API. Its always better to go with that, if available.

**Comment by neo1691** [comment]
I searched I couldn't find any!! My only option is to understand the json properly or scrap some other website.
