### ISSUE TITLE
Code breaks when there is no notification daemon working. 

### ISSUE THREAD

**Issue by neo1691** [neo1691/scorer.py#37]
Hi had a very interesting scenario on an ubuntu box where somehow the notification daemon was disabled. even ``notify-send`` was not working. The code failed with the following error:

Traceback (most recent call last):
  File "/usr/local/bin/scorer", line 9, in <module>
    load_entry_point('scorer==0.1', 'console_scripts', 'scorer')()
  File "/usr/local/lib/python2.7/dist-packages/scorer-0.1-py2.7.egg/scorer/app.py", line 38, in main
    notify.popUpMessage(title, score)
  File "/usr/local/lib/python2.7/dist-packages/scorer-0.1-py2.7.egg/scorer/notification.py", line 8, in popUpMessage
    pynotify.Notification(title, message, "dialog-information").show()
gio.Error: Could not connect: Connection refused

Need to handle this error better!

**Comment by saurabh-deochake** [comment]
Well, I was working on one project with pynotify module and I got exactly the same error. I suspect that the gio error is coming from DBus service. By the way, I was running my script with root and root had no ownership of Dbus service instance and that's why it gave me the error.

I ran the script again with normal user and it ran perfectly normal. Can you please check that?

**Comment by neo1691** [comment]
@saurabh-deochake Confirmed, I am able to get notifications when running the script with root!
